### ISSUE TITLE
Compile error: An export assignment cannot be used in a module with other exported elements.

### ISSUE THREAD

**Issue by robotlovesyou** [typed-typings/npm-react-router#7]
Hi. Using this definition I get a compile error:

`An export assignment cannot be used in a module with other exported elements.`

It appears to have an issue with the last line `export = ReactRouter;`

**Comment by unional** [comment]
I do not see that error. How do you get to that error?

**Comment by unional** [comment]
I guess are you installing it with `--global`? It should not

**Comment by robotlovesyou** [comment]
Hi. No, I'm installing it as a module. I am using typescript 2.0. Would
that make a difference?

**Comment by unional** [comment]
Nope. that should not make a difference.

**Comment by blakeembrey** [comment]
Have you installed it twice? Using a global and non-global version? You can probably see if you look at where the error is coming from whether it exists twice.

**Comment by robotlovesyou** [comment]
Damn. Yes. There is a version from definitely typed in here too.

Sorry.
